project:
  type: website
  output-dir: docs

website:
  title: "Okemo Onboarding"
  sidebar:
    contents: auto
format: 
  html:
    html-math-method: mathjax
    fig-responsive: true
    toc: true
    toc-location: left
    theme: cosmo
    page-layout: full
  ipynb:
    wrap: none
  pdf: 
    toc: false
